### ISSUE TITLE
[feature] Display a loading screen while the app is loading

### ISSUE THREAD

**Issue by syu93** [pinnackl/photos-contest-fb#15]
Display a loading screen while the app is loading

Because of the async behaviour of the app, we need to show the final page to the use after all have been load

**Comment by syu93** [comment]
Create simple page animation when the app is ready
http://pinnackl.com/index

``` css
.container{

    padding: 1em 4em 0;

    -moz-box-sizing: border-box;

    -webkit-box-sizing: border-box;

    box-sizing: border-box;
        animation-name: appear;
        animation-duration: 1s;
        animation-fill-mode: both;
}



@keyframes appear {

    0% {

        opacity: 0;

        transform: translateX(40px);

    }

    100% {

        opacity: 1;

        transform: translateX(0px);

    }

}

.appear {

    animation-name: appear;

}
```
